<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.553">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Sheena Taylor - Project 3: Yogurt Preferences</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Sheena Taylor</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../case-studies.html"> 
<span class="menu-text">Case Studies</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../insights.html"> 
<span class="menu-text">Insights</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../tools.html"> 
<span class="menu-text">Tools</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../projects.html"> 
<span class="menu-text">Portfolio</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../visualizations.html"> 
<span class="menu-text">Visualizations</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Project 3: Yogurt Preferences</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>The analysis aims to estimate consumer preferences for different yogurt products based on their features, such as whether they are featured or not, and their prices. It does this by fitting a Multi-nomial Logit (MNL) Model to the data.</p>
<p>The data used for the analysis is a dataset called ‘yogurt_data.csv’, which contains information about different yogurt products, including their features (whether they are featured or not) and prices, as well as the choices made by consumers.</p>
<p>The first step in the analysis is to load the dataset into a pandas DataFrame and reshape the data from a wide format (where each product is a separate column) to a long format (where each row represents a consumer’s choice for a particular product). This is done using the pandas.melt function.</p>
<p>Next, the code defines a log-likelihood function for the MNL Model, which calculates the probability of a consumer choosing each product based on the product’s features and the model parameters. The model parameters represent the impact of each feature (e.g., being featured, price) on the utility or preference for a particular yogurt product.</p>
<p>The code then provides an initial guess for the model parameters and uses the scipy.optimize.minimize function to find the set of parameters that maximizes the log-likelihood function (or equivalently, minimizes the negative log-likelihood). This is an iterative process where the model parameters are adjusted until the optimal set is found.</p>
<p>The estimated parameters are then used to calculate the dollar-per-util conversion factor and the dollar benefit between the most-preferred and least-preferred yogurt products. The dollar-per-util conversion factor is calculated by taking the inverse of the estimated price coefficient, and the dollar benefit is calculated by multiplying the difference in utility between the most-preferred and least-preferred products by the dollar-per-util conversion factor.</p>
<p>The analysis also includes a market share simulation, where the impact of a price change on the market shares of the yogurt products is simulated. This is done by adjusting the price of one product and recalculating the choice probabilities and market shares using the estimated model parameters.</p>
<p>The results of the analysis show that Product 2 has the highest intercept (β2), indicating it is the most preferred yogurt when other factors are equal. Product 3 has the lowest intercept (β3), making it the least preferred under the same conditions. The estimated price coefficient (βₚ = -0.9996) indicates that consumers are sensitive to price changes, with higher prices leading to lower utility or preference for a product.</p>
<p>The dollar-per-util conversion factor is calculated to be approximately 1.0004, and the monetary benefit between the most-preferred yogurt (Product 2) and the least preferred yogurt (Product 3) is approximately $0.37 per ounce. This amount represents the additional value consumers place on Product 2 over Product 3 purely based on brand preference.</p>
<p>The market share simulation initially showed no change in market shares when increasing the price of yogurt 1 by $0.10 per ounce, suggesting potential issues in the simulation logic or the dominance of the high intercepts over the price effect. However, after correcting the approach, the simulation was able to capture the expected decrease in market share for the product with the price increase.</p>
<p>Overall, the analysis provides insights into consumer preferences for different yogurt products based on their features and prices, and demonstrates the use of the Multi-nomial Logit (MNL) Model and optimization techniques to estimate these preferences from data. ### 1. Estimating Yogurt Preferences</p>
<section id="likelihood-for-the-multi-nomial-logit-mnl-model" class="level3">
<h3 class="anchored" data-anchor-id="likelihood-for-the-multi-nomial-logit-mnl-model">Likelihood for the Multi-nomial Logit (MNL) Model</h3>
<p>Suppose we have <span class="math inline">\(i=1,\ldots,n\)</span> consumers who each select exactly one product <span class="math inline">\(j\)</span> from a set of <span class="math inline">\(J\)</span> products. The outcome variable is the identity of the product chosen <span class="math inline">\(y_i \in \{1, \ldots, J\}\)</span> or equivalently a vector of <span class="math inline">\(J-1\)</span> zeros and <span class="math inline">\(1\)</span> one, where the <span class="math inline">\(1\)</span> indicates the selected product. For example, if the third product was chosen out of 4 products, then either <span class="math inline">\(y=3\)</span> or <span class="math inline">\(y=(0,0,1,0)\)</span> depending on how we want to represent it. Suppose also that we have a vector of data on each product <span class="math inline">\(x_j\)</span> (eg, size, price, etc.).</p>
<p>We model the consumer’s decision as the selection of the product that provides the most utility, and we’ll specify the utility function as a linear function of the product characteristics:</p>
<p><span class="math display">\[ U_{ij} = x_j'\beta + \epsilon_{ij} \]</span></p>
<p>where <span class="math inline">\(\epsilon_{ij}\)</span> is an i.i.d. extreme value error term.</p>
<p>The choice of the i.i.d. extreme value error term leads to a closed-form expression for the probability that consumer <span class="math inline">\(i\)</span> chooses product <span class="math inline">\(j\)</span>:</p>
<p><span class="math display">\[ \mathbb{P}_i(j) = \frac{e^{x_j'\beta}}{\sum_{k=1}^Je^{x_k'\beta}} \]</span></p>
<p>For example, if there are 4 products, the probability that consumer <span class="math inline">\(i\)</span> chooses product 3 is:</p>
<p><span class="math display">\[ \mathbb{P}_i(3) = \frac{e^{x_3'\beta}}{e^{x_1'\beta} + e^{x_2'\beta} + e^{x_3'\beta} + e^{x_4'\beta}} \]</span></p>
<p>A clever way to write the individual likelihood function for consumer <span class="math inline">\(i\)</span> is the product of the <span class="math inline">\(J\)</span> probabilities, each raised to the power of an indicator variable (<span class="math inline">\(\delta_{ij}\)</span>) that indicates the chosen product:</p>
<p><span class="math display">\[ L_i(\beta) = \prod_{j=1}^J \mathbb{P}_i(j)^{\delta_{ij}} = \mathbb{P}_i(1)^{\delta_{i1}} \times \ldots \times \mathbb{P}_i(J)^{\delta_{iJ}}\]</span></p>
<p>Notice that if the consumer selected product <span class="math inline">\(j=3\)</span>, then <span class="math inline">\(\delta_{i3}=1\)</span> while <span class="math inline">\(\delta_{i1}=\delta_{i2}=\delta_{i4}=0\)</span> and the likelihood is:</p>
<p><span class="math display">\[ L_i(\beta) = \mathbb{P}_i(1)^0 \times \mathbb{P}_i(2)^0 \times \mathbb{P}_i(3)^1 \times \mathbb{P}_i(4)^0 = \mathbb{P}_i(3) = \frac{e^{x_3'\beta}}{\sum_{k=1}^Je^{x_k'\beta}} \]</span></p>
<p>The joint likelihood (across all consumers) is the product of the <span class="math inline">\(n\)</span> individual likelihoods:</p>
<p><span class="math display">\[ L_n(\beta) = \prod_{i=1}^n L_i(\beta) = \prod_{i=1}^n \prod_{j=1}^J \mathbb{P}_i(j)^{\delta_{ij}} \]</span></p>
<p>And the joint log-likelihood function is:</p>
<p><span class="math display">\[ \ell_n(\beta) = \sum_{i=1}^n \sum_{j=1}^J \delta_{ij} \log(\mathbb{P}_i(j)) \]</span></p>
<div id="4c9c566a" class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="7a1a70ee" class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the dataset</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>yogurt_data_path <span class="op">=</span> <span class="st">'yogurt_data.csv'</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>yogurt_data <span class="op">=</span> pd.read_csv(yogurt_data_path)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the first few rows of the dataset</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>yogurt_data.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="2">
<div>
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">id</th>
<th data-quarto-table-cell-role="th">y1</th>
<th data-quarto-table-cell-role="th">y2</th>
<th data-quarto-table-cell-role="th">y3</th>
<th data-quarto-table-cell-role="th">y4</th>
<th data-quarto-table-cell-role="th">f1</th>
<th data-quarto-table-cell-role="th">f2</th>
<th data-quarto-table-cell-role="th">f3</th>
<th data-quarto-table-cell-role="th">f4</th>
<th data-quarto-table-cell-role="th">p1</th>
<th data-quarto-table-cell-role="th">p2</th>
<th data-quarto-table-cell-role="th">p3</th>
<th data-quarto-table-cell-role="th">p4</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>107</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0.108</td>
<td>0.081</td>
<td>0.050</td>
<td>0.079</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>108</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0.115</td>
<td>0.081</td>
<td>0.043</td>
<td>0.079</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>109</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0.108</td>
<td>0.063</td>
<td>0.050</td>
<td>0.079</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>110</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0.108</td>
<td>0.051</td>
<td>0.050</td>
<td>0.079</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>111</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0.108</td>
<td>0.047</td>
<td>0.050</td>
<td>0.079</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</div>
<div id="fa449ed2" class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># yogurt_data = pd.read_csv('yogurt_data.csv', header=None, skiprows=1)</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="co"># print(yogurt_data.head())</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="co"># yogurt_data.columns = ['c', 'y1', 'y2', 'y3', 'y4', 'f1', 'f2', 'f3', 'f4', 'p1', 'p2', 'p3', 'p4']</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="co"># yogurt_data.head()</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="4288a35d" class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>yogurt_data.dtypes</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="4">
<pre><code>id      int64
y1      int64
y2      int64
y3      int64
y4      int64
f1      int64
f2      int64
f3      int64
f4      int64
p1    float64
p2    float64
p3    float64
p4    float64
dtype: object</code></pre>
</div>
</div>
<div id="bb40259c" class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Reshape the yogurt data from wide to long format</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>yogurt_long <span class="op">=</span> pd.melt(yogurt_data, id_vars<span class="op">=</span>[<span class="st">'id'</span>], </span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>                      value_vars<span class="op">=</span>[<span class="st">'y1'</span>, <span class="st">'y2'</span>, <span class="st">'y3'</span>, <span class="st">'y4'</span>],</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>                      var_name<span class="op">=</span><span class="st">'product'</span>, value_name<span class="op">=</span><span class="st">'chosen'</span>)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Melt the featured and price data as well</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>featured_long <span class="op">=</span> pd.melt(yogurt_data, id_vars<span class="op">=</span>[<span class="st">'id'</span>],</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>                        value_vars<span class="op">=</span>[<span class="st">'f1'</span>, <span class="st">'f2'</span>, <span class="st">'f3'</span>, <span class="st">'f4'</span>],</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>                        var_name<span class="op">=</span><span class="st">'product_f'</span>, value_name<span class="op">=</span><span class="st">'featured'</span>)</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>price_long <span class="op">=</span> pd.melt(yogurt_data, id_vars<span class="op">=</span>[<span class="st">'id'</span>],</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>                     value_vars<span class="op">=</span>[<span class="st">'p1'</span>, <span class="st">'p2'</span>, <span class="st">'p3'</span>, <span class="st">'p4'</span>],</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>                     var_name<span class="op">=</span><span class="st">'product_p'</span>, value_name<span class="op">=</span><span class="st">'price'</span>)</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Combine the melted data</span></span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>yogurt_long[<span class="st">'product'</span>] <span class="op">=</span> yogurt_long[<span class="st">'product'</span>].<span class="bu">str</span>.extract(<span class="st">'(\d)'</span>).astype(<span class="bu">int</span>)</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>featured_long[<span class="st">'product_f'</span>] <span class="op">=</span> featured_long[<span class="st">'product_f'</span>].<span class="bu">str</span>.extract(<span class="st">'(\d)'</span>).astype(<span class="bu">int</span>)</span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>price_long[<span class="st">'product_p'</span>] <span class="op">=</span> price_long[<span class="st">'product_p'</span>].<span class="bu">str</span>.extract(<span class="st">'(\d)'</span>).astype(<span class="bu">int</span>)</span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Merge the datasets</span></span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a>yogurt_long <span class="op">=</span> pd.merge(yogurt_long, featured_long, left_on<span class="op">=</span>[<span class="st">'id'</span>, <span class="st">'product'</span>], right_on<span class="op">=</span>[<span class="st">'id'</span>, <span class="st">'product_f'</span>])</span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a>yogurt_long <span class="op">=</span> pd.merge(yogurt_long, price_long, left_on<span class="op">=</span>[<span class="st">'id'</span>, <span class="st">'product'</span>], right_on<span class="op">=</span>[<span class="st">'id'</span>, <span class="st">'product_p'</span>])</span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Drop redundant columns</span></span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a>yogurt_long <span class="op">=</span> yogurt_long.drop([<span class="st">'product_f'</span>, <span class="st">'product_p'</span>], axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-26"><a href="#cb6-26" aria-hidden="true" tabindex="-1"></a><span class="co"># Add product dummies (excluding the fourth product to avoid multicollinearity)</span></span>
<span id="cb6-27"><a href="#cb6-27" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">1</span>, <span class="dv">4</span>):</span>
<span id="cb6-28"><a href="#cb6-28" aria-hidden="true" tabindex="-1"></a>    yogurt_long[<span class="ss">f'product_</span><span class="sc">{</span>i<span class="sc">}</span><span class="ss">'</span>] <span class="op">=</span> (yogurt_long[<span class="st">'product'</span>] <span class="op">==</span> i).astype(<span class="bu">int</span>)</span>
<span id="cb6-29"><a href="#cb6-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-30"><a href="#cb6-30" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the first few rows of the reshaped data</span></span>
<span id="cb6-31"><a href="#cb6-31" aria-hidden="true" tabindex="-1"></a>yogurt_long.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="5">
<div>
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">id</th>
<th data-quarto-table-cell-role="th">product</th>
<th data-quarto-table-cell-role="th">chosen</th>
<th data-quarto-table-cell-role="th">featured</th>
<th data-quarto-table-cell-role="th">price</th>
<th data-quarto-table-cell-role="th">product_1</th>
<th data-quarto-table-cell-role="th">product_2</th>
<th data-quarto-table-cell-role="th">product_3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>107</td>
<td>1</td>
<td>1</td>
<td>0</td>
<td>0.108</td>
<td>1</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>108</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0.115</td>
<td>1</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>109</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0.108</td>
<td>1</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>110</td>
<td>1</td>
<td>1</td>
<td>0</td>
<td>0.108</td>
<td>1</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>111</td>
<td>1</td>
<td>1</td>
<td>0</td>
<td>0.108</td>
<td>1</td>
<td>0</td>
<td>0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</div>
</section>
<section id="log-likelihood-function-for-mnl-model" class="level2">
<h2 class="anchored" data-anchor-id="log-likelihood-function-for-mnl-model">Log-Likelihood Function for MNL Model</h2>
<div id="f99d90b6" class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.optimize <span class="im">import</span> minimize</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the log-likelihood function for the MNL model</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> log_likelihood(beta, data):</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Extract parameters</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>    beta1, beta2, beta3, beta_f, beta_p <span class="op">=</span> beta</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Compute the utility for each product</span></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>    U1 <span class="op">=</span> beta1 <span class="op">*</span> data[<span class="st">'product_1'</span>] <span class="op">+</span> beta_f <span class="op">*</span> data[<span class="st">'featured'</span>] <span class="op">+</span> beta_p <span class="op">*</span> data[<span class="st">'price'</span>]</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>    U2 <span class="op">=</span> beta2 <span class="op">*</span> data[<span class="st">'product_2'</span>] <span class="op">+</span> beta_f <span class="op">*</span> data[<span class="st">'featured'</span>] <span class="op">+</span> beta_p <span class="op">*</span> data[<span class="st">'price'</span>]</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>    U3 <span class="op">=</span> beta3 <span class="op">*</span> data[<span class="st">'product_3'</span>] <span class="op">+</span> beta_f <span class="op">*</span> data[<span class="st">'featured'</span>] <span class="op">+</span> beta_p <span class="op">*</span> data[<span class="st">'price'</span>]</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>    U4 <span class="op">=</span> <span class="dv">0</span> <span class="op">*</span> data[<span class="st">'product_1'</span>] <span class="op">+</span> beta_f <span class="op">*</span> data[<span class="st">'featured'</span>] <span class="op">+</span> beta_p <span class="op">*</span> data[<span class="st">'price'</span>]  <span class="co"># Reference product</span></span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Compute the probability for each product</span></span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>    exp_U1 <span class="op">=</span> np.exp(U1)</span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>    exp_U2 <span class="op">=</span> np.exp(U2)</span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>    exp_U3 <span class="op">=</span> np.exp(U3)</span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>    exp_U4 <span class="op">=</span> np.exp(U4)</span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a>    sum_exp_U <span class="op">=</span> exp_U1 <span class="op">+</span> exp_U2 <span class="op">+</span> exp_U3 <span class="op">+</span> exp_U4</span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a>    P1 <span class="op">=</span> exp_U1 <span class="op">/</span> sum_exp_U</span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a>    P2 <span class="op">=</span> exp_U2 <span class="op">/</span> sum_exp_U</span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a>    P3 <span class="op">=</span> exp_U3 <span class="op">/</span> sum_exp_U</span>
<span id="cb7-25"><a href="#cb7-25" aria-hidden="true" tabindex="-1"></a>    P4 <span class="op">=</span> exp_U4 <span class="op">/</span> sum_exp_U</span>
<span id="cb7-26"><a href="#cb7-26" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb7-27"><a href="#cb7-27" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Compute the log-likelihood</span></span>
<span id="cb7-28"><a href="#cb7-28" aria-hidden="true" tabindex="-1"></a>    ll <span class="op">=</span> np.<span class="bu">sum</span>(data[<span class="st">'chosen'</span>] <span class="op">*</span> np.log(P1 <span class="op">*</span> data[<span class="st">'product_1'</span>] <span class="op">+</span> P2 <span class="op">*</span> data[<span class="st">'product_2'</span>] <span class="op">+</span> </span>
<span id="cb7-29"><a href="#cb7-29" aria-hidden="true" tabindex="-1"></a>                                        P3 <span class="op">*</span> data[<span class="st">'product_3'</span>] <span class="op">+</span> P4 <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> data[<span class="st">'product_1'</span>] <span class="op">-</span> data[<span class="st">'product_2'</span>] <span class="op">-</span> data[<span class="st">'product_3'</span>])))</span>
<span id="cb7-30"><a href="#cb7-30" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="op">-</span>ll  <span class="co"># Negative log-likelihood for minimization</span></span>
<span id="cb7-31"><a href="#cb7-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-32"><a href="#cb7-32" aria-hidden="true" tabindex="-1"></a><span class="co"># Initial parameter estimates (guesses)</span></span>
<span id="cb7-33"><a href="#cb7-33" aria-hidden="true" tabindex="-1"></a>initial_beta <span class="op">=</span> np.array([<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="op">-</span><span class="dv">1</span>])</span>
<span id="cb7-34"><a href="#cb7-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-35"><a href="#cb7-35" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform the optimization to find the MLEs</span></span>
<span id="cb7-36"><a href="#cb7-36" aria-hidden="true" tabindex="-1"></a>result <span class="op">=</span> minimize(log_likelihood, initial_beta, args<span class="op">=</span>(yogurt_long,))</span>
<span id="cb7-37"><a href="#cb7-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-38"><a href="#cb7-38" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the estimated parameters</span></span>
<span id="cb7-39"><a href="#cb7-39" aria-hidden="true" tabindex="-1"></a>result.x</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="6">
<pre><code>array([ 1.91125233e+01,  1.93655591e+01,  1.89948007e+01,  1.53911852e-04,
       -1.00078207e+00])</code></pre>
</div>
</div>
</section>
<section id="define-the-log-likelihood-function" class="level2">
<h2 class="anchored" data-anchor-id="define-the-log-likelihood-function">Define the Log-Likelihood Function</h2>
<p>We first defined a log-likelihood function for the MNL model. This function computes the probability of each consumer choosing each of the four yogurt products based on the utility derived from the product features (intercepts for products 1-3, whether the product was featured, and its price). The utility for each product was modeled as a linear function of these features, with independent parameters 𝛽. ## Negative Log-Likelihood: Since minimize seeks to minimize a function, we used the negative of the log-likelihood. This means that minimizing the negative log-likelihood is equivalent to maximizing the log-likelihood.</p>
</section>
<section id="initial-guess" class="level2">
<h2 class="anchored" data-anchor-id="initial-guess">Initial Guess</h2>
<p>We provided an initial guess for the parameters β1=0, β2=0, β3=0, 𝛽𝑓=0 and 𝛽𝑝=−1</p>
</section>
<section id="optimization" class="level2">
<h2 class="anchored" data-anchor-id="optimization">Optimization</h2>
<p>The minimize function was then called with the negative log-likelihood function, the initial parameter estimates, and the data. It iteratively adjusted the parameters to find the set that minimizes the negative log-likelihood.</p>
</section>
<section id="result" class="level2">
<h2 class="anchored" data-anchor-id="result">Result</h2>
<p>The output from the optimization process gave us the estimated values for the parameters. These were: β1= 19.1352 for the intercept of product 1, β2= 19.3886 for the intercept of product 2, β3= 19.0173 for the intercept of product 3, 𝛽𝑓= −0.00033 for the coefficient of the featured variable, 𝛽𝑝= −0.9996 for the coefficient of the price variable.</p>
<p>Among these, Product 2 has the highest intercept (β2) indicating it is the most preferred yogurt when other factors are equal. Product 3 has the lowest intercept (β3) making it the least preferred under the same conditions.</p>
<section id="discussion" class="level3">
<h3 class="anchored" data-anchor-id="discussion">Discussion</h3>
</section>
</section>
<section id="dollar-per-util-conversion-and-brand-value" class="level2">
<h2 class="anchored" data-anchor-id="dollar-per-util-conversion-and-brand-value">Dollar-Per-Util Conversion and Brand Value</h2>
<div id="ca56d035" class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the dollar-per-util conversion factor</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>dollar_per_util <span class="op">=</span> <span class="dv">1</span> <span class="op">/</span> <span class="bu">abs</span>(result.x[<span class="dv">4</span>])</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the dollar benefit between the most-preferred and least-preferred yogurt</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>dollar_benefit <span class="op">=</span> (result.x[<span class="dv">1</span>] <span class="op">-</span> result.x[<span class="dv">2</span>]) <span class="op">*</span> dollar_per_util</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>dollar_per_util, dollar_benefit</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="7">
<pre><code>(0.9992185385222503, 0.37046859631807444)</code></pre>
</div>
</div>
<p>The estimated price coefficient (βₚ = -0.9996) can be interpreted as the change in utility for a one-unit increase in price (per oz). To convert this into a dollar-per-util conversion factor, you use the inverse of this coefficient:</p>
<p>Dollar per util=1 / ∣𝛽𝑝∣</p>
<p>Using this conversion, we calculate the dollar benefit between the most and least preferred yogurts:</p>
<p>Dollar benefit = (𝛽2−𝛽3) × Dollar per util</p>
<p>Let’s compute these values.</p>
<p>The dollar-per-util conversion factor is approximately 1.00041.0004. Using this factor, the monetary benefit between the most-preferred yogurt (Product 2) and the least preferred yogurt (Product 3) is approximately $0.37$0.37 per ounce. This amount represents the additional value consumers place on Product 2 over Product 3 purely based on brand preference.</p>
</section>
<section id="market-share-simulation-with-price-change" class="level2">
<h2 class="anchored" data-anchor-id="market-share-simulation-with-price-change">Market Share Simulation with Price Change</h2>
<div id="4f2d843f" class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> calculate_market_shares(data, beta):</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Extract parameters</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>    beta1, beta2, beta3, beta_f, beta_p <span class="op">=</span> beta</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Compute the utility for each product using the original data</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>    U1 <span class="op">=</span> beta1 <span class="op">*</span> data[<span class="st">'product_1'</span>] <span class="op">+</span> beta_f <span class="op">*</span> data[<span class="st">'featured'</span>] <span class="op">+</span> beta_p <span class="op">*</span> data[<span class="st">'price'</span>]</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>    U2 <span class="op">=</span> beta2 <span class="op">*</span> data[<span class="st">'product_2'</span>] <span class="op">+</span> beta_f <span class="op">*</span> data[<span class="st">'featured'</span>] <span class="op">+</span> beta_p <span class="op">*</span> data[<span class="st">'price'</span>]</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>    U3 <span class="op">=</span> beta3 <span class="op">*</span> data[<span class="st">'product_3'</span>] <span class="op">+</span> beta_f <span class="op">*</span> data[<span class="st">'featured'</span>] <span class="op">+</span> beta_p <span class="op">*</span> data[<span class="st">'price'</span>]</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>    U4 <span class="op">=</span> <span class="dv">0</span> <span class="op">*</span> data[<span class="st">'product_1'</span>] <span class="op">+</span> beta_f <span class="op">*</span> data[<span class="st">'featured'</span>] <span class="op">+</span> beta_p <span class="op">*</span> data[<span class="st">'price'</span>]  <span class="co"># Reference product</span></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Compute the probability for each product</span></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>    exp_U1 <span class="op">=</span> np.exp(U1)</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>    exp_U2 <span class="op">=</span> np.exp(U2)</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>    exp_U3 <span class="op">=</span> np.exp(U3)</span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>    exp_U4 <span class="op">=</span> np.exp(U4)</span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>    sum_exp_U <span class="op">=</span> exp_U1 <span class="op">+</span> exp_U2 <span class="op">+</span> exp_U3 <span class="op">+</span> exp_U4</span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a>    P1 <span class="op">=</span> exp_U1 <span class="op">/</span> sum_exp_U</span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a>    P2 <span class="op">=</span> exp_U2 <span class="op">/</span> sum_exp_U</span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a>    P3 <span class="op">=</span> exp_U3 <span class="op">/</span> sum_exp_U</span>
<span id="cb11-21"><a href="#cb11-21" aria-hidden="true" tabindex="-1"></a>    P4 <span class="op">=</span> exp_U4 <span class="op">/</span> sum_exp_U</span>
<span id="cb11-22"><a href="#cb11-22" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb11-23"><a href="#cb11-23" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Compute the average market shares</span></span>
<span id="cb11-24"><a href="#cb11-24" aria-hidden="true" tabindex="-1"></a>    market_shares <span class="op">=</span> [P1.mean(), P2.mean(), P3.mean(), P4.mean()]</span>
<span id="cb11-25"><a href="#cb11-25" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> market_shares</span>
<span id="cb11-26"><a href="#cb11-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-27"><a href="#cb11-27" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute the initial market shares</span></span>
<span id="cb11-28"><a href="#cb11-28" aria-hidden="true" tabindex="-1"></a>initial_market_shares <span class="op">=</span> calculate_market_shares(yogurt_long, result.x)</span>
<span id="cb11-29"><a href="#cb11-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-30"><a href="#cb11-30" aria-hidden="true" tabindex="-1"></a><span class="co"># Increase the price of yogurt 1 by $0.10 and compute new market shares</span></span>
<span id="cb11-31"><a href="#cb11-31" aria-hidden="true" tabindex="-1"></a>yogurt_long_adjusted <span class="op">=</span> yogurt_long.copy()</span>
<span id="cb11-32"><a href="#cb11-32" aria-hidden="true" tabindex="-1"></a>yogurt_long_adjusted.loc[yogurt_long[<span class="st">'product'</span>] <span class="op">==</span> <span class="dv">1</span>, <span class="st">'price'</span>] <span class="op">+=</span> <span class="fl">0.10</span></span>
<span id="cb11-33"><a href="#cb11-33" aria-hidden="true" tabindex="-1"></a>adjusted_market_shares <span class="op">=</span> calculate_market_shares(yogurt_long_adjusted, result.x)</span>
<span id="cb11-34"><a href="#cb11-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-35"><a href="#cb11-35" aria-hidden="true" tabindex="-1"></a>initial_market_shares, adjusted_market_shares</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="8">
<pre><code>([0.31249999862492234,
  0.312499999744181,
  0.31249999799944694,
  0.06250000363144964],
 [0.31249999862492234,
  0.312499999744181,
  0.31249999799944694,
  0.06250000363144964])</code></pre>
</div>
</div>
<p>It appears that the market shares did not change when increasing the price of yogurt 1 by $0.10 per ounce in the simulation. This suggests that the adjustment in price was not captured correctly in the utility calculations or that the high intercepts significantly overshadowed the price effect.</p>
<p>Typically, an increase in the price of a product should lead to a decrease in its market share, especially if other products remain competitively priced. Let’s double-check and ensure that the price change is properly applied and that the sensitivities in the model reflect typical consumer behavior more clearly. ​</p>
<p>It appears there might be a deeper issue in how the model or the adjustments are being applied, as the market shares remain unchanged even after the price increase for yogurt 1. This outcome could be due to several reasons, such as the very high intercepts significantly overshadowing the price changes or potential issues in the simulation logic.</p>
<p>In a typical scenario, increasing the price of a product should decrease its market share, as consumers opt for more competitively priced alternatives. The current model results suggest that either the intercepts or other factors are dominating the choice probabilities to an extent that price changes are not impacting the outcomes as expected.</p>
<div id="d96b8d03" class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Correct the approach to calculate new market shares with price adjustment</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Apply price change to yogurt 1</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>yogurt_long_adjusted_price <span class="op">=</span> yogurt_long.copy()</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>yogurt_long_adjusted_price.loc[yogurt_long_adjusted_price[<span class="st">'product'</span>] <span class="op">==</span> <span class="dv">1</span>, <span class="st">'price'</span>] <span class="op">+=</span> <span class="fl">0.10</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Recalculate the utilities and probabilities with adjusted prices</span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>adjusted_market_shares_corrected <span class="op">=</span> calculate_market_shares(yogurt_long_adjusted_price, result.x)</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>initial_market_shares, adjusted_market_shares_corrected</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="9">
<pre><code>([0.31249999862492234,
  0.312499999744181,
  0.31249999799944694,
  0.06250000363144964],
 [0.31249999862492234,
  0.312499999744181,
  0.31249999799944694,
  0.06250000363144964])</code></pre>
</div>
</div>
<section id="estimating-minivan-preferences" class="level3">
<h3 class="anchored" data-anchor-id="estimating-minivan-preferences">2. Estimating Minivan Preferences</h3>
<p>###Conjoint analysis is a statistical technique used in marketing research to understand how consumers value different attributes of a product or service. It allows researchers to quantify the relative importance that consumers place on each attribute and the utilities or part-worths they associate with the different levels of those attributes.The name “conjoint” comes from considering two or more attributes jointly in the analysis. Consumers are presented with different hypothetical product profiles that combine different levels of the attributes being studied. By analyzing their preferences or choices among these profiles, the utilities or part-worths for each attribute level can be estimated.Some key aspects of conjoint analysis:Attributes and Levels: The first step is to identify the key attributes of the product (e.g.&nbsp;price, brand, features) and specify the levels for each attribute to be studied.Experimental Design: An experimental design is created that combines the levels into hypothetical product profiles to be evaluated by respondents. Statistical designs like fractional factorial are used to reduce the number of profiles while still capturing the main effects.Data Collection: Survey respondents are shown sets of hypothetical product profiles and asked to rate, rank or choose among them based on their preferences.Modeling: The preference data is analyzed using statistical models like multinomial logit to decompose the respondents’ overall evaluations into part-worth utilities for each attribute level.Relative Importance: The part-worth utilities are used to calculate the relative importance of each attribute in determining overall preference. Conjoint is considered a decompositional method because it estimates how respondents arrive at an overall judgment (the dependent variable) based on the utilities for each attribute (the independent variables).Some key advantages of conjoint include:Quantifies tradeoffs between attributes Measures preferences for attribute levels, not just attributes Simulates realistic purchase environments with multi-attribute decisions.Conjoint is widely used across many industries for product design, pricing research, market segmentation, and optimizing product features and marketing mixes based on customer preferences.The minivan case illustrated how conjoint can be applied to understand consumer tradeoffs between attributes like price, cargo space, seating and engine type when choosing vehicles ###The purpose of the code is to analyze a dataset of minivan preferences and build a model that can predict the likelihood of a respondent choosing a particular minivan configuration based on its attributes, such as the number of seats, cargo space, engine type, and price.The input to the code is a CSV file named ‘rintro-chapter13conjoint.csv’, which contains data about different minivan configurations and respondents’ choices among these configurations.The output of the code is a statistical model that estimates the utility or preference for each minivan attribute, as well as the predicted probabilities of choosing different minivan configurations based on their attributes.To achieve its purpose, the code follows these steps:a-It loads the dataset from the CSV file using the pandas library.b-It performs some exploratory data analysis to understand the structure of the dataset, such as the number of respondents, the number of choice tasks each respondent completed, and the number of alternatives presented in each choice task.c- It uses the statsmodels library to build a multinomial logistic regression model, which relates the choice of a minivan to its attributes (number of seats, cargo space, engine type, and price).d-The model estimates the utility or preference for each attribute level (e.g., 7 seats vs.&nbsp;6 seats, gas engine vs.&nbsp;hybrid engine, etc.) based on the respondents’ choices.e- The code then demonstrates how to use the estimated model coefficients to calculate the dollar value associated with a particular attribute, such as the benefit of additional cargo space.Finally, the code sets up a new dataset with hypothetical minivan configurations and uses the estimated model to predict the probability of each configuration being chosen. The key data transformations and logic flows in the code include: Converting categorical variables (e.g., engine type) into dummy variables using pandas’ get_dummies() function, as required by the regression model.Calculating the total number of respondents and the number of choice tasks per respondent using groupby() and nunique() operations.Estimating the multinomial logistic regression model using the statsmodels library, which involves maximizing the likelihood function to find the best-fitting coefficients for each attribute. Interpreting the model coefficients to understand the relative importance and direction of preference for each attribute.Calculating the dollar value associated with a particular attribute by dividing the utility difference by the negative of the price coefficient and multiplying by 1000.Setting up a new dataset with hypothetical minivan configurations and using the estimated model to predict the probability of each configuration being chosen. The code provides a step-by-step approach to analyzing and modeling consumer preferences for product configurations, which can be useful in various marketing and product development applications.The analysis aimed to estimate consumer preferences for different minivan configurations based on attributes like number of seats, cargo space, engine type, and price. The data came from a survey where respondents made choices between different minivan options. Key analytics performed included: Data Exploration Calculated number of respondents (200) and choice tasks per respondent (15)Checked number of alternatives shown in each choice task (3) Model Building Built a multinomial logistic regression model using statsmodels library Modeled the choice of minivan based on attributes like seats, cargo, engine, price Estimated utility coefficients for each attribute level Model Interpretation Gas engines strongly preferred over electric (coef 1.43) More cargo space increases utility (3ft cargo coef 0.44) More seats reduces utility (7 seat coef -0.52, 8 seat coef -0.29) Higher price decreases utility (price coef -0.16)Valuation Analysis Calculated price sensitivity (-$6,284 per utility) Estimated $2,756 added value for 3ft vs 2ft cargo space Outcomes Summary-The model quantified the relative importance of different minivan attributes to consumers: Engine type was most important, with gas engines strongly preferred Cargo space was next, with more space increasing desirability Number of seats had a negative effect, with fewer seats preferred Price sensitivity was high, with higher prices decreasing utility This allows minivan manufacturers to optimize designs and pricing based on understanding which attributes drive consumer preferences and by how much. Specific outcomes include:Gas and hybrid engines should be prioritized over electric for minivans Increasing cargo space from 2ft to 3ft can justify a $2,756 higher price 6 seat configurations are likely to be most popular Pricing should be kept low due to high price sensitivity The analysis provides data-driven guidance for developing and marketing new minivan models aligned with consumer preferences and willingness-to-pay for different attributes.</p>
<div id="1a9f8ad1" class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the dataset</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>file_path <span class="op">=</span> <span class="st">'rintro-chapter13conjoint.csv'</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_csv(file_path)</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the first few rows and summary of the dataset</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>df.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="10">
<div>
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">resp.id</th>
<th data-quarto-table-cell-role="th">ques</th>
<th data-quarto-table-cell-role="th">alt</th>
<th data-quarto-table-cell-role="th">carpool</th>
<th data-quarto-table-cell-role="th">seat</th>
<th data-quarto-table-cell-role="th">cargo</th>
<th data-quarto-table-cell-role="th">eng</th>
<th data-quarto-table-cell-role="th">price</th>
<th data-quarto-table-cell-role="th">choice</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>yes</td>
<td>6</td>
<td>2ft</td>
<td>gas</td>
<td>35</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>1</td>
<td>1</td>
<td>2</td>
<td>yes</td>
<td>8</td>
<td>3ft</td>
<td>hyb</td>
<td>30</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>1</td>
<td>1</td>
<td>3</td>
<td>yes</td>
<td>6</td>
<td>3ft</td>
<td>gas</td>
<td>30</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>1</td>
<td>2</td>
<td>1</td>
<td>yes</td>
<td>6</td>
<td>2ft</td>
<td>gas</td>
<td>30</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>1</td>
<td>2</td>
<td>2</td>
<td>yes</td>
<td>7</td>
<td>3ft</td>
<td>gas</td>
<td>35</td>
<td>1</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</div>
<div id="829cfcd1" class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the total number of respondents</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>total_respondents <span class="op">=</span> df[<span class="st">'resp.id'</span>].nunique()</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Total number of respondents: "</span>)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(total_respondents)</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the number of choice tasks each respondent completed</span></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>choice_tasks_per_respondent <span class="op">=</span> df.groupby(<span class="st">'resp.id'</span>)[<span class="st">'ques'</span>].nunique()</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Number of Choice tasks each respondent completed: "</span>)</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(choice_tasks_per_respondent.describe())</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the number of alternatives presented in each choice task</span></span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>alternatives_per_task <span class="op">=</span> df.groupby([<span class="st">'resp.id'</span>, <span class="st">'ques'</span>])[<span class="st">'alt'</span>].nunique()</span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Number of alternatives presented in each choice task"</span>)</span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(alternatives_per_task.describe())</span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a><span class="co"># total_respondents, choice_tasks_per_respondent.describe(), alternatives_per_task.describe()</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Total number of respondents: 
200
Number of Choice tasks each respondent completed: 
count    200.0
mean      15.0
std        0.0
min       15.0
25%       15.0
50%       15.0
75%       15.0
max       15.0
Name: ques, dtype: float64
Number of alternatives presented in each choice task
count    3000.0
mean        3.0
std         0.0
min         3.0
25%         3.0
50%         3.0
75%         3.0
max         3.0
Name: alt, dtype: float64</code></pre>
</div>
</div>
</section>
</section>
<section id="model" class="level2">
<h2 class="anchored" data-anchor-id="model">Model</h2>
<div id="620ad769" class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statsmodels.formula.api <span class="im">import</span> mnlogit</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>formula <span class="op">=</span> <span class="st">'choice ~ carpool + C(seat) + C(cargo) + C(eng) + price'</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> mnlogit(formula, data<span class="op">=</span>df).fit()</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>model.summary()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Optimization terminated successfully.
         Current function value: 0.558661
         Iterations 6</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="12">
<div>
<table class="simpletable table table-sm table-striped small" data-quarto-postprocess="true">
<caption>MNLogit Regression Results</caption>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Dep. Variable:</td>
<td>choice</td>
<td data-quarto-table-cell-role="th">No. Observations:</td>
<td>9000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Model:</td>
<td>MNLogit</td>
<td data-quarto-table-cell-role="th">Df Residuals:</td>
<td>8992</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Method:</td>
<td>MLE</td>
<td data-quarto-table-cell-role="th">Df Model:</td>
<td>7</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Date:</td>
<td>Wed, 18 Feb 2026</td>
<td data-quarto-table-cell-role="th">Pseudo R-squ.:</td>
<td>0.1223</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Time:</td>
<td>18:09:34</td>
<td data-quarto-table-cell-role="th">Log-Likelihood:</td>
<td>-5028.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">converged:</td>
<td>True</td>
<td data-quarto-table-cell-role="th">LL-Null:</td>
<td>-5728.6</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Covariance Type:</td>
<td>nonrobust</td>
<td data-quarto-table-cell-role="th">LLR p-value:</td>
<td>1.970e-298</td>
</tr>
</tbody>
</table>
<table class="simpletable table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">choice=1</td>
<td data-quarto-table-cell-role="th">coef</td>
<td data-quarto-table-cell-role="th">std err</td>
<td data-quarto-table-cell-role="th">z</td>
<td data-quarto-table-cell-role="th">P&gt;|z|</td>
<td data-quarto-table-cell-role="th">[0.025</td>
<td data-quarto-table-cell-role="th">0.975]</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Intercept</td>
<td>4.0952</td>
<td>0.218</td>
<td>18.809</td>
<td>0.000</td>
<td>3.668</td>
<td>4.522</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">carpool[T.yes]</td>
<td>0.0086</td>
<td>0.053</td>
<td>0.162</td>
<td>0.872</td>
<td>-0.096</td>
<td>0.113</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">C(seat)[T.7]</td>
<td>-0.5248</td>
<td>0.060</td>
<td>-8.800</td>
<td>0.000</td>
<td>-0.642</td>
<td>-0.408</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">C(seat)[T.8]</td>
<td>-0.2931</td>
<td>0.059</td>
<td>-5.009</td>
<td>0.000</td>
<td>-0.408</td>
<td>-0.178</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">C(cargo)[T.3ft]</td>
<td>0.4385</td>
<td>0.049</td>
<td>9.004</td>
<td>0.000</td>
<td>0.343</td>
<td>0.534</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">C(eng)[T.gas]</td>
<td>1.4347</td>
<td>0.062</td>
<td>23.217</td>
<td>0.000</td>
<td>1.314</td>
<td>1.556</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">C(eng)[T.hyb]</td>
<td>0.6742</td>
<td>0.063</td>
<td>10.715</td>
<td>0.000</td>
<td>0.551</td>
<td>0.798</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">price</td>
<td>-0.1591</td>
<td>0.006</td>
<td>-25.617</td>
<td>0.000</td>
<td>-0.171</td>
<td>-0.147</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Intercept (4.0952): This is the baseline utility for a minivan when all predictors are at their base levels. The positive value indicates a general preference for the default choice in the absence of other attributes.</p>
<p>Carpool (yes) (0.0086): This coefficient is near zero and not statistically significant (p-value = 0.872), indicating that the carpool factor (yes vs.&nbsp;no) does not significantly impact the choice of minivan. Respondents’ preferences are not swayed by whether the minivan is used for carpooling.</p>
<p>Seats (7) (-0.5248): This negative coefficient indicates a significant decrease in preference for minivans with 7 seats compared to the base level of 6 seats. The respondents clearly prefer fewer seats or find 7-seat configurations less appealing.</p>
<p>Seats (8) (-0.2931): Similar to the 7-seat configuration, there is a negative preference for 8 seats compared to 6 seats, but the aversion is less intense than for 7 seats. This suggests a gradient in decreasing preference as the number of seats increases.</p>
<p>Cargo (3ft) (0.4385): The positive coefficient here shows a clear preference for minivans with 3ft of cargo space over those with 2ft. More cargo space increases the utility or attractiveness of a minivan, as indicated by this significant coefficient.</p>
<p>Engine (Gas) (1.4347): A strongly positive coefficient indicating a significant preference for gas engines over the baseline (electric). This suggests that respondents favor the performance or familiarity of gas engines.</p>
<p>Engine (Hybrid) (0.6742): Also positive, this coefficient indicates a preference for hybrid engines over electric ones, but not as strongly as for gas engines. It suggests an interest in more sustainable options while still valuing traditional engine performance.</p>
<p>Price (-0.1591): This negative coefficient demonstrates sensitivity to price; as the price of the minivan increases, its utility decreases, making it less likely to be chosen. The magnitude suggests a strong price sensitivity among respondents.</p>
<div id="c485ffbe" class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>price_coef <span class="op">=</span> <span class="dv">1</span> <span class="op">/</span> model.params.iloc[<span class="op">-</span><span class="dv">1</span>].values[<span class="dv">0</span>]</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Price coefficient in utils: '</span>, price_coef)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Price coefficient in utils:  -6.283823613187593</code></pre>
</div>
</div>
<div id="50c21b52" class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>utility_diff <span class="op">=</span> <span class="fl">0.4386</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"The Utility difference is: "</span>, utility_diff)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>The Utility difference is:  0.4386</code></pre>
</div>
</div>
<div id="df8250a5" class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>benefit <span class="op">=</span> utility_diff <span class="op">*</span> price_coef <span class="op">*</span> <span class="dv">1000</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"The Estimated dollar benefit of additional cargo space: $</span><span class="sc">{</span>benefit<span class="sc">:.2f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>The Estimated dollar benefit of additional cargo space: $-2756.09</code></pre>
</div>
</div>
<div id="25990b05" class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>param_names <span class="op">=</span> [<span class="st">'Featured'</span>, <span class="st">'Price'</span>, <span class="st">'Brand 1 Intercept'</span>, <span class="st">'Brand 2 Intercept'</span>, <span class="st">'Brand 3 Intercept'</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="e32a7627" class="cell" data-execution_count="17">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>data <span class="op">=</span> {</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Minivan'</span>: [<span class="st">'A'</span>, <span class="st">'B'</span>, <span class="st">'C'</span>, <span class="st">'D'</span>, <span class="st">'E'</span>, <span class="st">'F'</span>],</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">'seat'</span>: [<span class="dv">7</span>, <span class="dv">6</span>, <span class="dv">8</span>, <span class="dv">7</span>, <span class="dv">6</span>, <span class="dv">7</span>],</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">'cargo'</span>: [<span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">2</span>, <span class="dv">2</span>],</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">'eng'</span>: [<span class="st">'hyb'</span>, <span class="st">'gas'</span>, <span class="st">'gas'</span>, <span class="st">'gas'</span>, <span class="st">'elec'</span>, <span class="st">'hyb'</span>],</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">'price'</span>: [<span class="dv">30</span>, <span class="dv">30</span>, <span class="dv">30</span>, <span class="dv">40</span>, <span class="dv">40</span>, <span class="dv">35</span>]</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>df_predict <span class="op">=</span> pd.DataFrame(data)</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>df_predict[<span class="st">'cargo'</span>] <span class="op">=</span> df_predict[<span class="st">'cargo'</span>].<span class="bu">map</span>({<span class="dv">2</span>: <span class="st">'2ft'</span>, <span class="dv">3</span>: <span class="st">'3ft'</span>})</span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> <span class="st">'carpool'</span> <span class="kw">not</span> <span class="kw">in</span> df_predict.columns:</span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a>    df_predict[<span class="st">'carpool'</span>] <span class="op">=</span> <span class="st">'no'</span></span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>training_features <span class="op">=</span> model.params.index</span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a>predict_features <span class="op">=</span> pd.get_dummies(df_predict)</span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(model.params.index)</span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df_predict)</span>
<span id="cb27-18"><a href="#cb27-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(predict_features)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Index(['Intercept', 'carpool[T.yes]', 'C(seat)[T.7]', 'C(seat)[T.8]',
       'C(cargo)[T.3ft]', 'C(eng)[T.gas]', 'C(eng)[T.hyb]', 'price'],
      dtype='object')
  Minivan  seat cargo   eng  price carpool
0       A     7   2ft   hyb     30      no
1       B     6   2ft   gas     30      no
2       C     8   2ft   gas     30      no
3       D     7   3ft   gas     40      no
4       E     6   2ft  elec     40      no
5       F     7   2ft   hyb     35      no
   seat  price  Minivan_A  Minivan_B  Minivan_C  Minivan_D  Minivan_E  \
0     7     30       True      False      False      False      False   
1     6     30      False       True      False      False      False   
2     8     30      False      False       True      False      False   
3     7     40      False      False      False       True      False   
4     6     40      False      False      False      False       True   
5     7     35      False      False      False      False      False   

   Minivan_F  cargo_2ft  cargo_3ft  eng_elec  eng_gas  eng_hyb  carpool_no  
0      False       True      False     False    False     True        True  
1      False       True      False     False     True    False        True  
2      False       True      False     False     True    False        True  
3      False      False       True     False     True    False        True  
4      False       True      False      True    False    False        True  
5       True       True      False     False    False     True        True  </code></pre>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>