---
title: "About"
---
“We’re here to put a dent in the universe. 
Otherwise why else even be here?
 -Steve Jobs

Sheena Taylor is a versatile data-driven marketing and sales professional with a unique background in management and client success. Leveraging her robust foundation in Python and hands-on experience with key data science libraries such as NumPy, Pandas, and Scikit-learn, Sheena excels in employing innovative methodologies to solve complex problems and deliver tailored solutions that align with clients' project objectives and budget constraints.

Driven by a strong analytical mindset and a commitment to staying abreast of industry trends, Sheena seamlessly integrates qualitative and quantitative insights to inform strategic decision-making and drive measurable business impact. Her adaptability, attention to detail, and effective communication skills enable her to collaborate cross-functionally and forge lasting partnerships with stakeholders. Sheena is a resourceful, resilient force to be reckoned with, thriving in ambiguous situations and embracing challenges as opportunities for growth.

With a keen eye for detail and a passion for continuous learning, Sheena is adept at utilizing various advanced analytical methods to extract meaningful insights from data. She is well-versed in data cleaning and preprocessing techniques, ensuring the quality and integrity of datasets for analysis. Additionally, Sheena specializes in predictive modeling, employing machine learning algorithms to forecast future trends and behaviors, thereby empowering businesses to make informed decisions.

Moreover, Sheena possesses strong communication skills, enabling her to effectively convey insights and recommendations to stakeholders in a clear and actionable manner. Whether leading small-scale initiatives or spearheading large-scale projects on digital platforms, Sheena demonstrates a knack for driving results and achieving measurable outcomes.

In her pursuit of expanding her intellectual horsepower, Sheena delves into diverse methodologies such as conjoint analysis and Bayesian inference. These techniques allow her to explore new avenues of problem-solving and gain a deeper understanding of consumer preferences and behavior, ultimately contributing to her ability to make a positive impact in the world and the global economy.

With a passion for learning and a commitment to excellence, Sheena Taylor continues to push the boundaries of innovation in data-driven marketing and sales, consistently delivering value to clients and driving business growth in a dynamic digital landscape.


Leaders start with the customer and work backwards. They work vigorously to earn and keep customer trust. Although leaders pay attention to competitors, they obsess over customers.

- Ownership: Think long-term, act for the entire company, never say "that's not my job."

- Invent and Simplify: Expect innovation, find ways to simplify, look for new ideas from everywhere.

- Learn and Be Curious: Never stop learning, seek to improve, explore new possibilities.

- Insist on the Highest Standards: Relentlessly high standards, continually raise the bar, deliver high-quality.

- Think Big: Create and communicate a bold direction, think differently, look for ways to serve customers.

- Bias for Action: Value calculated risk-taking, speed matters in business.

- Frugality: Accomplish more with less, constraints breed resourcefulness and invention.

- Earn Trust: Listen attentively, speak candidly, treat others respectfully, benchmark against the best.

- Dive Deep: Operate at all levels, stay connected to details, audit frequently, be skeptical when metrics differ.

- Have Backbone; Disagree and Commit: Challenge decisions respectfully, have conviction, commit wholly.

- Deliver Results: Focus on key inputs, deliver with quality and timeliness, rise to the occasion.

- Success and Scale Bring Broad Responsibility: Be humble, thoughtful about secondary effects, make better every day, leave things better than found.

